-- MySQL Script generated by MySQL Workbench
-- Mon May 20 17:13:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articulos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` DECIMAL(2) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `descripcion`, `nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articulospedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`articulospedido` (
  `idpedido` INT NOT NULL,
  `idarticulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`idpedido`, `idarticulo`),
  INDEX `idarticulo_idx` (`idarticulo` ASC),
  CONSTRAINT `idpedido`
    FOREIGN KEY (`idpedido`)
    REFERENCES `mydb`.`Pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idarticulo`
    FOREIGN KEY (`idarticulo`)
    REFERENCES `mydb`.`Articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mesa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReservaMesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ReservaMesa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numComensales` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(150) NOT NULL,
  `hora` VARCHAR(45) NOT NULL,
  `dia` DATE NOT NULL,
  `idmesa` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idmesa_idx` (`idmesa` ASC),
  CONSTRAINT `idmesa`
    FOREIGN KEY (`idmesa`)
    REFERENCES `mydb`.`Mesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombreTItular` VARCHAR(45) NULL,
  `fcaducidad` DATE NULL,
  `precio` DECIMAL(2) NOT NULL,
  `numtarjeta` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
